image: node:6.7.0

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "StrictHostKeyChecking no " > /root/.ssh/config
    - npm --registry=https://registry.npm.taobao.org install
    - npm run compile
  only:
    - master
  tags:
    - build-node

deploy:
  stage: deploy
  script:
    - cd /home/ops/production/apiGateway
    - git checkout master
    - git reset --hard HEAD
    - git clean -f -d
    - git pull
    - npm --registry=https://registry.npm.taobao.org install
    - npm run compile
    - rm -Rf dist
    - pm2 restart apiGateway
  only:
    - master
  tags:
    - deploy-ssh
