image: node:6.2.1

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

job1:
  stage: build
  script:
    - npm --registry=https://registry.npm.taobao.org install
    - npm run compile
  only:
    - master
  tags:
    - build-node
