image: node

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

job1:
  stage: build
  script:
    - echo 'alias cnpm="npm --registry=https://registry.npm.taobao.org --cache=$HOME/.npm/.cache/cnpm --disturl=https://npm.taobao.org/dist --userconfig=$HOME/.cnpmrc"' >> ~/.bashrc && source ~/.bashrc
    - cnpm install
    - npm run compile
  only:
    - master
  tags:
    - build-node
